# Generated by Django 3.2.12 on 2022-05-02 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0004_alter_photoentry_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoentry',
            name='photo_location',
            field=models.TextField(blank=True, verbose_name='Lieu de la photo'),
        ),
    ]
