# Generated by Django 3.2.12 on 2022-05-02 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0006_alter_photoentry_submitted_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoentry',
            name='photographer_comments',
            field=models.TextField(blank=True, verbose_name='Vos commentaires sur la photo'),
        ),
    ]
