# Generated by Django 4.0.4 on 2022-07-19 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0007_alter_photoentry_photographer_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoentry',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 7, 1, 0, 0), verbose_name='Date de soumission'),
            preserve_default=False,
        ),
    ]
