# Generated by Django 4.0.7 on 2022-10-18 13:29

from django.db import migrations
import hashlib
import time


def gen_sha1(apps, schema_editor):
    PhotoEntry = apps.get_model("photo", "PhotoEntry")
    for entry in PhotoEntry.objects.all():
        if entry.sha1_name is None:
            sha1_name = hashlib.sha1(
                (str(time.monotonic_ns()) + "|" + str(entry.user.id)).encode(
                    "utf-8"
                )
            ).hexdigest()
            entry.sha1_name = sha1_name
            entry.save()


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0011_photoentry_sha1_name"),
    ]

    operations = [
        migrations.RunPython(gen_sha1, reverse_code=migrations.RunPython.noop),
    ]
