# Generated by Django 4.1.3 on 2022-12-25 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("photo", "0014_alter_photoentry_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photoentry",
            name="pedestrian_issues_md",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Remarques piétons (markdown)",
            ),
        ),
        migrations.AlterField(
            model_name="photoentry",
            name="submitter_info_md",
            field=models.TextField(
                blank=True,
                null=True,
                verbose_name="Remarques photo (markdown)",
            ),
        ),
    ]
