# Generated by Django 3.0.3 on 2020-02-13 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SurveyQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.CharField(max_length=10)),
                ('sort_index', models.IntegerField()),
                ('question_title', models.CharField(max_length=200)),
                ('question_text', models.TextField()),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validated', models.BooleanField()),
                ('commune', models.CharField(max_length=100)),
                ('liste', models.CharField(max_length=100)),
                ('tete_de_liste', models.CharField(max_length=100)),
                ('email_liste', models.CharField(max_length=100)),
                ('email_person', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('twitter_liste', models.CharField(max_length=100)),
                ('twitter_candidat', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey')),
            ],
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_question_response', models.TextField()),
                ('survey_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.Survey')),
                ('survey_question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.SurveyQuestion')),
                ('survey_responder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='surveys.SurveyResponder')),
            ],
        ),
    ]
