# Generated by Django 4.2.13 on 2024-06-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0004_auto_20210119_0833"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="identifier",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="identifier",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="surveyresponder",
            name="identifier",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="surveyresponse",
            name="identifier",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
