# Generated by Django 4.2.13 on 2024-06-21 13:45

from django.db import migrations
from django.utils.crypto import get_random_string


def update_survey_identifiers(apps, schema_editor):
    Survey = apps.get_model("surveys", "Survey")
    for survey in Survey.objects.all():
        survey.identifier = get_random_string(length=10)
        survey.save()

    SurveyQuestion = apps.get_model("surveys", "SurveyQuestion")
    for survey_question in SurveyQuestion.objects.all():
        survey_question.identifier = get_random_string(length=20)
        survey_question.save()

    SurveyResponder = apps.get_model("surveys", "SurveyResponder")
    for survey_responder in SurveyResponder.objects.all():
        survey_responder.identifier = get_random_string(length=20)
        survey_responder.save()

    SurveyResponse = apps.get_model("surveys", "SurveyResponse")
    for survey_response in SurveyResponse.objects.all():
        survey_response.identifier = get_random_string(length=20)
        survey_response.save()


class Migration(migrations.Migration):
    dependencies = [
        (
            "surveys",
            "0005_survey_identifier_surveyquestion_identifier_and_more",
        ),
    ]

    operations = [
        migrations.RunPython(update_survey_identifiers),
    ]
