# Generated by Django 4.2.13 on 2024-06-21 14:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0006_set_unique_identifiers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyquestion",
            name="identifier",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="surveyresponder",
            name="identifier",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="surveyresponse",
            name="identifier",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
