# Generated by Django 4.2.13 on 2024-06-21 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0007_alter_surveyquestion_identifier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveycommune",
            name="identifier",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="survey",
            name="identifier",
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
