# Generated by Django 4.2.13 on 2024-06-21 14:22

from django.db import migrations
from django.utils.crypto import get_random_string


def update_survey_identifiers(apps, schema_editor):
    Commune = apps.get_model("surveys", "SurveyCommune")
    for commune in Commune.objects.all():
        commune.identifier = get_random_string(length=20)
        commune.save()


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0008_surveycommune_identifier_alter_survey_identifier"),
    ]

    operations = [
        migrations.RunPython(update_survey_identifiers),
    ]
