# Generated by Django 4.2.13 on 2024-06-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0009_set_unique_identifier_commune"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveycommune",
            name="identifier",
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
