# Generated by Django 4.2.13 on 2024-06-21 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0010_alter_surveycommune_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveycommune",
            name="survey",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="surveys.survey",
            ),
        ),
    ]
