# Generated by Django 4.2.13 on 2024-06-21 16:34

from django.db import migrations


def set_commune_survey(apps, schema_editor):
    SurveyCommune = apps.get_model("surveys", "SurveyCommune")
    SurveyResponder = apps.get_model("surveys", "SurveyResponder")

    commune_count = 0
    for commune in SurveyCommune.objects.all():
        # Get the first related SurveyResponder object (assuming there
        # is at least one).  We expect all responders with a given
        # commune to belong to the same survey, although this wasn't
        # initially modeled.
        responder = SurveyResponder.objects.filter(commune=commune).first()
        if responder:
            commune.survey = responder.survey
            commune.save()
            commune_count += 1
        else:
            print(f"Commune {commune} with id={commune.id} has no responders")
    print(
        f"Set survey for {commune_count} communes of"
        f" {SurveyCommune.objects.count()} total communes."
    )


class Migration(migrations.Migration):
    dependencies = [
        ("surveys", "0011_surveycommune_survey"),
    ]

    operations = [
        migrations.RunPython(set_commune_survey),
    ]
