# Generated by Django 3.0.3 on 2020-05-09 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_name', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('template_name', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='ClusterBlogCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=40)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusterblog.ClusterBlog')),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='ClusterBlogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('image_filename', models.CharField(max_length=80)),
                ('approved', models.BooleanField(default=False)),
                ('og_title', models.CharField(blank=True, max_length=80)),
                ('og_description', models.TextField()),
                ('og_image', models.CharField(blank=True, max_length=80)),
                ('og_image_alt', models.TextField(blank=True)),
                ('og_image_type', models.CharField(blank=True, max_length=40)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clusterblog.ClusterBlogCategory')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clusterblog.ClusterBlog')),
            ],
            options={
                'verbose_name_plural': 'ClusterBlogEntries',
            },
        ),
    ]
