# Generated by Django 3.0.3 on 2020-05-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clusterblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clusterblogcategory',
            name='random_entries_stick_to_category',
            field=models.BooleanField(default=False),
        ),
    ]
