# Generated by Django 3.0.7 on 2021-04-26 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clusterblog', '0002_clusterblogcategory_random_entries_stick_to_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clusterblogcategory',
            name='cluster',
        ),
        migrations.RemoveField(
            model_name='clusterblogentry',
            name='category',
        ),
        migrations.RemoveField(
            model_name='clusterblogentry',
            name='cluster',
        ),
        migrations.DeleteModel(
            name='ClusterBlog',
        ),
        migrations.DeleteModel(
            name='ClusterBlogCategory',
        ),
        migrations.DeleteModel(
            name='ClusterBlogEntry',
        ),
    ]
