# Generated by Django 3.0.7 on 2020-06-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observatoire', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='observatoire',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
