# Generated by Django 3.0.7 on 2020-06-28 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observatoire', '0003_auto_20200628_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservatoireObjective',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(max_length=200)),
                ('objective_descr', models.TextField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observatoire.ObservatoirePerson')),
            ],
        ),
        migrations.CreateModel(
            name='ObservatoireProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_time', models.DateTimeField(auto_now_add=True)),
                ('progress', models.TextField()),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='observatoire.ObservatoireObjective')),
            ],
        ),
    ]
