# Generated by Django 3.0.7 on 2021-05-19 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoplan', '0002_mapcontent_mapdefinition_maplayer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MapPage',
        ),
    ]
