# Generated by Django 3.0.7 on 2021-05-24 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoplan', '0003_delete_mappage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapdefinition',
            name='public_description_md',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='mapdefinition',
            name='public_title',
            field=models.CharField(default='', max_length=80),
        ),
    ]
