# Generated by Django 3.0.7 on 2020-11-21 19:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mailing_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailingListEvents',
            new_name='MailingListEvent',
        ),
    ]
