# Generated by Django 3.0.7 on 2021-01-16 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0003_mailinglist_list_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailinglist',
            name='is_petition',
            field=models.BooleanField(default=False),
        ),
    ]
