# Generated by Django 3.0.7 on 2021-02-03 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_list", "0005_petition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="petition",
            name="slug",
            field=models.SlugField(
                allow_unicode=True, max_length=70, unique=True
            ),
        ),
    ]
