# Generated by Django 4.0.4 on 2022-05-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0011_mailinglist_mailing_list_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='mailing_list_type',
            field=models.CharField(blank=True, choices=[('NEWSLETTER', 'Newsletter'), ('PETITION', 'Petition'), ('PRESS', 'Press'), ('DONORS', 'Donors')], max_length=30, null=True),
        ),
    ]
