# Generated by Django 4.0.4 on 2022-06-30 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0012_alter_mailinglist_mailing_list_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailinglist',
            name='linked_article',
            field=models.SlugField(blank=True, max_length=90, null=True),
        ),
    ]
