# Generated by Django 4.0.4 on 2022-09-18 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_url', models.CharField(max_length=300)),
                ('session_id', models.CharField(max_length=200)),
                ('campaign', models.CharField(blank=True, max_length=100)),
                ('content', models.CharField(blank=True, max_length=100)),
                ('medium', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('term', models.CharField(blank=True, max_length=100)),
                ('aclk', models.BooleanField(blank=True, default=False)),
                ('fbclid', models.BooleanField(blank=True, default=False)),
                ('gclid', models.BooleanField(blank=True, default=False)),
                ('msclkid', models.BooleanField(blank=True, default=False)),
                ('twclid', models.BooleanField(blank=True, default=False)),
                ('ua_device', models.CharField(blank=True, max_length=100)),
                ('ua_os', models.CharField(blank=True, max_length=100)),
                ('ua_browser', models.CharField(blank=True, max_length=100)),
                ('ua_is_table', models.BooleanField(blank=True, default=False)),
                ('ua_is_mobile', models.BooleanField(blank=True, default=False)),
                ('ua_is_touch_capable', models.BooleanField(blank=True, default=False)),
                ('ua_is_pc', models.BooleanField(blank=True, default=False)),
                ('ua_is_bot', models.BooleanField(blank=True, default=False)),
                ('ua_is_email_client', models.BooleanField(blank=True, default=False)),
                ('user_is_authenticated', models.BooleanField(blank=True, default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
