# Generated by Django 4.0.4 on 2022-09-18 17:01

from django.db import migrations
from django.db import transaction


def copy_utm_to_gom_jabbar(apps, schema_editor):
    """

    We can't import the Person model directly as it may be a newer
    version than this migration expects. We use the historical version.
    """
    uVisit = apps.get_model('utm', 'Visit')
    gjVisit = apps.get_model('gom_jabbar', 'Visit')
    for utm in uVisit.objects.all():
        with transaction.atomic():
            gj_visit = gjVisit()
            gj_visit.base_url = utm.base_url;
            gj_visit.session_id = utm.session_id;
            gj_visit.campaign = utm.campaign;
            gj_visit.content = utm.content;
            gj_visit.medium = utm.medium;
            gj_visit.source = utm.source;
            gj_visit.term = utm.term;
            gj_visit.aclk = utm.aclk;
            gj_visit.fbclid = utm.fbclid;
            gj_visit.gclid = utm.gclid;
            gj_visit.msclkid = utm.msclkid;
            gj_visit.twclid = utm.twclid;
            gj_visit.ua_device = utm.ua_device;
            gj_visit.ua_os = utm.ua_os;
            gj_visit.ua_browser = utm.ua_browser;
            gj_visit.ua_is_table = utm.ua_is_table;
            gj_visit.ua_is_mobile = utm.ua_is_mobile;
            gj_visit.ua_is_touch_capable = utm.ua_is_touch_capable;
            gj_visit.ua_is_pc = utm.ua_is_pc;
            gj_visit.ua_is_bot = utm.ua_is_bot;
            gj_visit.ua_is_email_client = utm.ua_is_email_client;
            gj_visit.user_is_authenticated = utm.user_is_authenticated;
            gj_visit.timestamp = utm.timestamp;
            gj_visit.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gom_jabbar', '0001_initial'),
        ('utm', '0007_rename_utm_visit'),
    ]

    operations = [
        migrations.RunPython(copy_utm_to_gom_jabbar),
    ]
