# Generated by Django 4.0.4 on 2022-09-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gom_jabbar', '0002_auto_20220918_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=200, unique=True)),
                ('visits_from_humans', models.IntegerField()),
                ('visits_from_non_humans', models.IntegerField()),
            ],
        ),
    ]
