# Generated by Django 4.0.4 on 2022-07-05 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('zip_code', models.CharField(blank=True, max_length=5)),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField(auto_now_add=True)),
                ('number_of_pedestrians', models.IntegerField(default=0)),
                ('number_of_bicycles', models.IntegerField(default=0)),
                ('number_of_cars', models.IntegerField(default=0)),
                ('number_of_public_transports', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
