# Generated by Django 4.0.4 on 2022-07-18 08:20

from django.db import migrations, models
import django.db.models.deletion
import mobilito.models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilito', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('postcode', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('start_timestamp', models.DateTimeField()),
                ('end_timestamp', models.DateTimeField(blank=True, null=True)),
                ('pedestrian_count', models.IntegerField(null=True)),
                ('bicycle_count', models.IntegerField(null=True)),
                ('motor_vehicle_count', models.IntegerField(null=True)),
                ('public_transport_count', models.IntegerField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobilito.mobilitouser')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('ped', 'Pedestrian'), ('bike', 'Bicycle'), ('car', 'Motor Vehicle'), ('TC', 'Public Transport')], max_length=50, validators=[mobilito.models.event_type_validator])),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mobilito.session')),
            ],
        ),
    ]
