# Generated by Django 4.0.4 on 2022-07-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilito', '0002_event_session_delete_recording_event_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='total_number_of_bicycles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='total_number_of_motor_vehicles',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='total_number_of_pedestrians',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='total_number_of_public_transports',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='user_agent_browser',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='postcode',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
