# Generated by Django 4.0.4 on 2022-08-03 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilito', '0004_session_user_browser'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilitouser',
            name='completed_tutorial_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
