# Generated by Django 4.0.7 on 2022-09-28 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobilito', '0007_session_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_sha1',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
