# Generated by Django 4.0.7 on 2022-09-28 09:00

from django.db import migrations
import hashlib
import time


def gen_sha1(apps, schema_editor):
    Session = apps.get_model("mobilito", "Session")
    for session in Session.objects.all():
        if session.session_sha1 is None:
            session_sha1 = hashlib.sha1(
                (
                    str(time.monotonic_ns()) + "|" + str(session.user.user.id)
                ).encode("utf-8")
            ).hexdigest()
            session.session_sha1 = session_sha1
            session.save()


class Migration(migrations.Migration):

    dependencies = [
        ("mobilito", "0008_session_session_sha1"),
    ]

    operations = [
        migrations.RunPython(gen_sha1, reverse_code=migrations.RunPython.noop),
    ]
