# Generated by Django 4.0.7 on 2022-09-26 14:06

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Session = apps.get_model('mobilito', 'Session')
    for session in Session.objects.all():
        session.uuid = uuid.uuid4()
        session.save()


class Migration(migrations.Migration):

    dependencies = [
        ('mobilito', '0008_session_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
