# Generated by Django 4.0.7 on 2022-09-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobilito", "0009_auto_20220928_0900"),
    ]

    operations = [
        migrations.AlterField(
            model_name="session",
            name="session_sha1",
            field=models.CharField(
                max_length=200, unique=True, editable=False
            ),
        ),
    ]
