# Generated by Django 4.1.3 on 2022-11-07 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mobilito", "0013_inappropriateflag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="inappropriateflag",
            name="reporter_ip_address",
        ),
    ]
