# Generated by Django 4.1.3 on 2023-01-10 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobilito", "0014_remove_inappropriateflag_reporter_ip_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="mobilitosession",
            name="map_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="mobilito/map_images/"
            ),
        ),
    ]
