# Generated by Django 3.0.7 on 2021-06-30 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donator',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=13)),
                ('gender', models.CharField(choices=[('M', 'Monsieur'), ('MME', 'Madame')], max_length=3)),
                ('address', models.CharField(max_length=50)),
                ('more_adress', models.CharField(blank=True, max_length=50)),
                ('postal_code', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('SUB', 'Subscription'), ('PAY', 'One time donation')], max_length=50)),
                ('amount', models.FloatField()),
                ('donator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stripe_app.Donator')),
            ],
        ),
    ]
