# Generated by Django 3.0.7 on 2021-07-27 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0002_donation_donator'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
