# Generated by Django 3.2 on 2021-09-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stripe_app", "0002_donation_more_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="originating_parameters",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="donation",
            name="originating_view",
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
