# Generated by Django 3.2 on 2021-09-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stripe_app", "0002_donation_more_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="trackingprogression",
            name="user_agent",
            field=models.CharField(
                max_length=255, null=True, verbose_name="User agent"
            ),
        ),
    ]
