# Generated by Django 3.2.5 on 2021-09-28 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stripe_app", "0003_auto_20210923_1039"),
        ("stripe_app", "0003_trackingprogression_user_agent"),
    ]

    operations = []
