# Generated by Django 3.0.7 on 2021-07-28 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0004_auto_20210728_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donator',
            name='address',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='donator',
            name='city',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='donator',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donator',
            name='gender',
            field=models.CharField(choices=[('M', 'Monsieur'), ('MME', 'Madame')], max_length=3, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='donator',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='donator',
            name='more_adress',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='donator',
            name='postal_code',
            field=models.CharField(max_length=50),
        ),
    ]
