# Generated by Django 3.2.5 on 2021-10-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0006_auto_20211011_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='stripe_customer_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
