# Generated by Django 3.0.7 on 2021-07-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0005_tracking_step_rename'),
        ('stripe_app', '0006_auto_20210728_0948'),
    ]

    operations = [
    ]
