# Generated by Django 3.2.11 on 2022-02-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stripe_app", "0007_donation_stripe_customer_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="stripe_event_id",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
