# Generated by Django 3.2.13 on 2022-05-17 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0008_donation_stripe_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_source',
            field=models.CharField(default='stripe', max_length=100),
        ),
    ]
