# Generated by Django 3.0.7 on 2021-08-02 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0008_donator_to_donor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donor',
            old_name='gender',
            new_name='title',
        ),
    ]
