# Generated by Django 3.0.7 on 2021-08-02 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0009_auto_20210802_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='title',
            field=models.CharField(choices=[('M', 'Monsieur'), ('MME', 'Madame'), ('MMM', 'Autre')], max_length=3, verbose_name='Title'),
        ),
    ]
