# Generated by Django 3.0.7 on 2021-08-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0010_auto_20210802_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor',
            name='telephone',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
