# Generated by Django 3.0.7 on 2021-08-02 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0011_auto_20210802_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='amount',
            new_name='amount_centimes_euros',
        ),
    ]
