# Generated by Django 3.0.7 on 2021-08-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_app', '0012_amount_to_centimes_rename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount_centimes_euros',
            field=models.IntegerField(default=0, verbose_name='Amount in centimes'),
        ),
    ]
