# Generated by Django 3.2.5 on 2021-12-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utm', '0002_auto_20211213_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utm',
            old_name='session_cookie',
            new_name='session_id',
        ),
    ]
