# Generated by Django 4.0.4 on 2022-09-18 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utm', '0006_utm_user_is_authenticated'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UTM',
            new_name='Visit',
        ),
    ]
