# Generated by Django 3.0.7 on 2021-01-03 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicblogpage',
            name='body2_md',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topicblogpage',
            name='body3_md',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topicblogpage',
            name='bullet_image_1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='topicblogpage',
            name='bullet_image_2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='topicblogpage',
            name='bullet_image_3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='topicblogpage',
            name='bullet_image_4',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='topicblogpage',
            name='bullet_image_5',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='topicblogpage',
            name='bullet_text_1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topicblogpage',
            name='bullet_text_2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topicblogpage',
            name='bullet_text_4',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topicblogpage',
            name='bullet_text_5',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topicblogpage',
            name='hero_image',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='topicblogpage',
            name='hero_text',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='topicblogpage',
            name='meta_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topicblogpage',
            name='middle_image',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='topicblogpage',
            name='og_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topicblogpage',
            name='og_title',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='topicblogpage',
            name='twitter_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topicblogpage',
            name='twitter_title',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
