# Generated by Django 3.0.7 on 2021-01-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topicblog", "0003_auto_20210103_1755"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicblogpage",
            name="hero_description",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
