# Generated by Django 3.0.7 on 2021-01-03 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topicblog', '0004_topicblogpage_hero_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicblogpage',
            old_name='hero_text',
            new_name='hero_title',
        ),
    ]
