# Generated by Django 3.0.7 on 2021-01-03 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicblog', '0006_topicblogpage_middle_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicblogpage',
            name='body1_md',
            field=models.TextField(blank=True),
        ),
    ]
