# Generated by Django 3.2 on 2021-10-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topicblog", "0010_topicblogitem_topicblogtemplate"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicblogtemplate",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("article", "article"),
                    ("project", "project"),
                    ("press_release", "press_release"),
                    ("newsletter", "newsletter"),
                    ("newsletter_web", "newsletter_web"),
                    ("petition", "petition"),
                    ("mailing_list_signup", "mailing_list_signup"),
                ],
                default="article",
                max_length=100,
            ),
        ),
    ]
