# Generated by Django 3.2.5 on 2021-11-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicblog', '0018_auto_20211111_1801'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicblogitem',
            name='published',
        ),
        migrations.AlterField(
            model_name='topicblogitem',
            name='servable',
            field=models.BooleanField(default=False),
        ),
    ]
