# Generated by Django 3.2.5 on 2021-12-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topicblog", "0019_auto_20211116_1401"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicblogitem",
            name="date_modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
