# Generated by Django 3.2.5 on 2022-01-15 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topicblog", "0023_alter_topicblogitem_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topicblogitem",
            name="header_slug",
        ),
        migrations.RemoveField(
            model_name="topicblogitem",
            name="item_sort_key",
        ),
        migrations.RemoveField(
            model_name="topicblogitem",
            name="servable",
        ),
        migrations.AddField(
            model_name="topicblogitem",
            name="first_publication_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
