# Generated by Django 3.2.11 on 2022-01-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicblog', '0026_auto_20220117_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicblogemail',
            name='author_notes',
            field=models.TextField(blank=True, help_text='Notes pour éditeurs : ne seront pas affichées sur le site', null=True, verbose_name='Notes libres pour éditeurs'),
        ),
        migrations.AddField(
            model_name='topicblogitem',
            name='author_notes',
            field=models.TextField(blank=True, help_text='Notes pour éditeurs : ne seront pas affichées sur le site', null=True, verbose_name='Notes libres pour éditeurs'),
        ),
    ]
