# Generated by Django 3.2.11 on 2022-01-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicblog', '0026_auto_20220117_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicblogemail',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='topicblogitem',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
