# Generated by Django 3.2.11 on 2022-01-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topicblog", "0027_auto_20220120_1456"),
    ]

    operations = [
        migrations.AddField(
            model_name="topicblogemail",
            name="template_name",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="topicblogitem",
            name="template_name",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
