# Generated by Django 3.2.12 on 2022-03-06 15:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("mailing_list", "0009_alter_mailinglist_options"),
        ("topicblog", "0031_auto_20220202_1401"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicBlogPressSendRecord",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, max_length=90
                    ),
                ),
                ("send_time", models.DateTimeField(auto_now=True)),
                ("open_time", models.DateTimeField()),
                ("click_time", models.DateTimeField()),
                ("unsubscribe_time", models.DateTimeField()),
                (
                    "mailinglist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="mailing_list.mailinglist",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopicBlogPressClicks",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("click_time", models.DateTimeField()),
                ("click_url", models.CharField(max_length=1024)),
                (
                    "press",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="topicblog.topicblogpresssendrecord",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TopicBlogPress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, max_length=90
                    ),
                ),
                (
                    "publication_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "first_publication_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("template_name", models.CharField(blank=True, max_length=80)),
                ("title", models.CharField(blank=True, max_length=100)),
                ("header_title", models.CharField(blank=True, max_length=80)),
                (
                    "header_description",
                    models.CharField(blank=True, max_length=120),
                ),
                (
                    "social_description",
                    models.TextField(
                        blank=True,
                        help_text="Notes pour humains des objectifs (marketing) de la page",
                    ),
                ),
                ("twitter_title", models.CharField(blank=True, max_length=80)),
                ("twitter_description", models.TextField(blank=True)),
                (
                    "twitter_image",
                    models.ImageField(
                        blank=True,
                        help_text="2:1, résolution minimum : 300x157, max 4096x4096",
                        upload_to="twitter/",
                    ),
                ),
                ("og_title", models.CharField(blank=True, max_length=80)),
                ("og_description", models.TextField(blank=True)),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        help_text="résolution recommandée : 1200x630",
                        upload_to="opengraph/",
                    ),
                ),
                (
                    "author_notes",
                    models.TextField(
                        blank=True,
                        help_text="Notes pour éditeurs : ne seront pas affichées sur le site",
                        null=True,
                        verbose_name="Notes libres pour éditeurs",
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=80)),
                (
                    "header_image",
                    models.ImageField(
                        blank=True,
                        help_text="résolution recommandée : 1600x500",
                        upload_to="header/",
                    ),
                ),
                ("body_text_1_md", models.TextField(blank=True)),
                (
                    "body_image_1",
                    models.ImageField(
                        blank=True,
                        help_text="résolution recommandée : 1600x500",
                        upload_to="body/",
                    ),
                ),
                (
                    "body_image_1_alt_text",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "publisher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (
                    ("tbp.may_view", "May view unpublished TopicBlogPresss"),
                    ("tbp.may_edit", "May create and modify TopicBlogPresss"),
                    ("tbp.may_publish", "May publish TopicBlogPresss"),
                    (
                        "tbp.may_publish_self",
                        "May publish own TopicBlogPresss",
                    ),
                    ("tbp.may_send", "May send TopicBlogPresss"),
                    ("tbp.may_send_self", "May send own TopicBlogPresss"),
                ),
            },
        ),
    ]
