# Generated by Django 3.2.12 on 2022-03-06 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("topicblog", "0033_alter_topicblogpress_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopicBlogLauncher",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, max_length=90
                    ),
                ),
                (
                    "publication_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "first_publication_date",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("date_modified", models.DateTimeField(auto_now=True)),
                ("template_name", models.CharField(blank=True, max_length=80)),
                ("headline", models.CharField(blank=True, max_length=80)),
                ("launcher_text_md", models.TextField(blank=True)),
                (
                    "launcher_image",
                    models.ImageField(
                        blank=True,
                        help_text="résolution recommandée : 667x667",
                        upload_to="launcher/",
                    ),
                ),
                (
                    "launcher_image_alt_text",
                    models.CharField(blank=True, max_length=100),
                ),
                (
                    "article_slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, max_length=90
                    ),
                ),
                ("campaign_name", models.CharField(blank=True, max_length=80)),
                (
                    "publisher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "permissions": (
                    (
                        "tbla.may_view",
                        "May view unpublished TopicBlogLauncher",
                    ),
                    (
                        "tbla.may_edit",
                        "May create and modify TopicBlogLauncher",
                    ),
                    ("tbla.may_publish", "May publish TopicBlogLauncher"),
                    (
                        "tbla.may_publish_self",
                        "May publish own TopicBlogLauncher",
                    ),
                    ("tbla.may_send", "May send TopicBlogLaunchers"),
                    ("tbla.may_send_self", "May send own TopicBlogLauncher"),
                ),
            },
        ),
    ]
