# Generated by Django 3.2.12 on 2022-03-16 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topicblog', '0034_topicbloglauncher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicblogitem',
            options={'permissions': (('tbi.may_view', 'May view unpublished TopicBlogItems'), ('tbi.may_edit', 'May create and modify TopicBlogItems'), ('tbi.may_publish', 'May publish TopicBlogItems'), ('tbi.may_publish_self', 'May publish own TopicBlogItems'), ('tbi.may_retire', 'May retire TopicBlogItems'))},
        ),
    ]
