# Generated by Django 3.2.11 on 2022-03-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicblog', '0035_auto_20220314_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicbloglauncher',
            name='teaser_words',
            field=models.IntegerField(blank=True, default=50),
        ),
    ]
