# Generated by Django 3.2.12 on 2022-04-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topicblog', '0037_auto_20220403_0759'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topicbloglauncher',
            old_name='teaser_words',
            new_name='teaser_chars',
        ),
    ]
