# Generated by Django 3.2.12 on 2022-04-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicblog', '0039_topicblogmailinglistpitch'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicblogmailinglistpitch',
            name='subscription_form_button_label',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='topicblogmailinglistpitch',
            name='subscription_form_title',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
