# Generated by Django 3.2.13 on 2022-05-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "topicblog",
            "0042_rename_teaser_chars_topicbloglauncher_teaser_words",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="topicbloglauncher",
            old_name="teaser_words",
            new_name="teaser_chars",
        ),
    ]
