# Generated by Django 3.2.13 on 2022-05-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicblog', '0044_auto_20220517_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicblogemailsendrecord',
            name='send_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topicblogpresssendrecord',
            name='send_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
