# Generated by Django 3.2.13 on 2022-05-18 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicblog', '0045_auto_20220518_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicblogemailsendrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='topicblogpresssendrecord',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=50),
        ),
    ]
