# Generated by Django 4.0.4 on 2022-05-23 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicblog', '0047_sendrecordtransactional'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendrecordtransactional',
            name='aws_message_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='topicblogemailsendrecord',
            name='aws_message_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='topicblogpresssendrecord',
            name='aws_message_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
