# Generated by Django 4.0.4 on 2022-06-02 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topicblog', '0048_sendrecordtransactional_aws_message_id_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='topicblogemailsendrecord',
            constraint=models.UniqueConstraint(fields=('recipient', 'slug'), name='TBE_unique_recipient_slug'),
        ),
        migrations.AddConstraint(
            model_name='topicblogpresssendrecord',
            constraint=models.UniqueConstraint(fields=('recipient', 'slug'), name='TBP_unique_recipient_slug'),
        ),
    ]
