# Generated by Django 4.0.4 on 2022-06-20 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topicblog", "0051_alter_sendrecordmarketingemail_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sendrecordmarketingemail",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RETRY", "Retry"),
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="sendrecordmarketingpress",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RETRY", "Retry"),
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="sendrecordtransactional",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("RETRY", "Retry"),
                    ("SENT", "Sent"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
    ]
