# Generated by Django 4.0.4 on 2022-06-21 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topicblog', '0052_alter_sendrecordmarketingemail_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topicblogemail',
            options={'permissions': (('tbe.may_view', 'May view unpublished TopicBlogEmails'), ('tbe.may_edit', 'May create and modify TopicBlogEmails'), ('tbe.may_publish', 'May publish TopicBlogEmails'), ('tbe.may_publish_self', 'May publish own TopicBlogEmails'), ('tbe.may_send', 'May send TopicBlogEmails'), ('tbe.may_send_self', 'May send own TopicBlogEmails'), ('tbe.may_delete', 'May delete TopicBlogEmails'), ('tbe.may_delete_self', 'May delete own TopicBlogEmails'))},
        ),
        migrations.AlterModelOptions(
            name='topicblogitem',
            options={'permissions': (('tbi.may_view', 'May view unpublished TopicBlogItems'), ('tbi.may_edit', 'May create and modify TopicBlogItems'), ('tbi.may_publish', 'May publish TopicBlogItems'), ('tbi.may_publish_self', 'May publish own TopicBlogItems'), ('tbi.may_delete', 'May delete TopicBlogItems'), ('tbi.may_delete_self', 'May delete own TopicBlogItems'))},
        ),
        migrations.AlterModelOptions(
            name='topicbloglauncher',
            options={'permissions': (('tbla.may_view', 'May view unpublished TopicBlogLauncher'), ('tbla.may_edit', 'May create and modify TopicBlogLauncher'), ('tbla.may_publish', 'May publish TopicBlogLauncher'), ('tbla.may_publish_self', 'May publish own TopicBlogLauncher'), ('tbla.may_delete', 'May delete TopicBlogLauncher'), ('tbla.may_delete_self', 'May delete own TopicBlogLauncher'))},
        ),
        migrations.AlterModelOptions(
            name='topicblogmailinglistpitch',
            options={'permissions': (('tbmlp.may_view', 'May view unpublished TopicBlogMailingListPitch'), ('tbmlp.may_edit', 'May create and modify TopicBlogMailingListPitch'), ('tbmlp.may_publish', 'May publish TopicBlogMailingListPitch'), ('tbmlp.may_publish_self', 'May publish own TopicBlogMailingListPitch'), ('tbmlp.may_delete', 'May delete TopicBlogMailingListPitch'), ('tbmlp.may_delete_self', 'May delete own TopicBlogMailingListPitch')), 'verbose_name_plural': 'Mailing list pitches'},
        ),
        migrations.AlterModelOptions(
            name='topicblogpress',
            options={'permissions': (('tbp.may_view', 'May view unpublished TopicBlogPress'), ('tbp.may_edit', 'May create and modify TopicBlogPress'), ('tbp.may_publish', 'May publish TopicBlogPress'), ('tbp.may_publish_self', 'May publish own TopicBlogPress'), ('tbp.may_send', 'May send TopicBlogPresss'), ('tbp.may_send_self', 'May send own TopicBlogPress'), ('tbp.may_delete', 'May delete TopicBlogPress'), ('tbp.may_delete_self', 'May delete own TopicBlogPress'))},
        ),
    ]
