# Generated by Django 4.0.4 on 2022-08-09 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_list', '0013_alter_mailinglist_linked_article'),
        ('topicblog', '0058_alter_topicblogmailinglistpitch_mailing_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('subject', models.TextField(blank=True)),
                ('mailing_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mailing_list.mailinglist')),
            ],
        ),
        migrations.AddField(
            model_name='sendrecordmarketingemail',
            name='email_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='topicblog.emailcampaign'),
        ),
        migrations.AddField(
            model_name='sendrecordmarketingpress',
            name='email_campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='topicblog.emailcampaign'),
        ),
    ]
