# Generated by Django 4.0.7 on 2022-09-21 08:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('topicblog', '0060_auto_20220829_0948'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicBlogWrapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=90)),
                ('publication_date', models.DateTimeField(blank=True, null=True)),
                ('first_publication_date', models.DateTimeField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('scheduled_for_deletion_date', models.DateTimeField(blank=True, null=True)),
                ('social_description', models.TextField(blank=True, help_text='Notes pour humains des objectifs (marketing) de la page')),
                ('twitter_title', models.CharField(blank=True, max_length=80)),
                ('twitter_description', models.TextField(blank=True)),
                ('twitter_image', models.ImageField(blank=True, help_text='2:1, résolution minimum : 300x157, max 4096x4096', upload_to='twitter/')),
                ('og_title', models.CharField(blank=True, max_length=80)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, help_text='résolution recommandée : 1200x630', upload_to='opengraph/')),
                ('author_notes', models.TextField(blank=True, help_text='Notes pour éditeurs : ne seront pas affichées sur le site', null=True, verbose_name='Notes libres pour éditeurs')),
                ('underlying_slug', models.SlugField(allow_unicode=True, blank=True, max_length=300, null=True, verbose_name='Slug sous-jacent')),
                ('original_model', models.CharField(choices=[('topicblogitem', 'Article de blog'), ('topicblogmailinglistpitch', 'Inscription'), ('topicblogemail', 'Mail'), ('topicblogpress', 'Communiqué de presse')], default='topicblogitem', max_length=200, verbose_name='Type de contenu')),
                ('template_name', models.CharField(default='default', max_length=200)),
                ('publisher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Topic blog wrappers',
                'permissions': (('tbw.may_view', 'May view the list of existing wrappers'), ('tbw.may_edit', 'May create and edit TopicBlogWrapper'), ('tbw.may_publish', 'May publish TopicBlogWrapper'), ('tbw.may_publish_self', 'May publish own TopicBlogWrapper')),
            },
        ),
    ]
