# Generated by Django 4.0.4 on 2022-08-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('dashboard.may_see', 'May see dashboard'),),
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
