# Generated by Django 3.0.7 on 2020-11-02 07:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('clickcollect', '0003_auto_20201102_0715'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clickandcollect',
            name='reserve_date',
        ),
        migrations.AddField(
            model_name='clickandcollect',
            name='reserve_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
