# Generated by Django 3.0.7 on 2020-11-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clickcollect', '0004_auto_20201102_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickablecollectable',
            name='collectable_token',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
