# Generated by Django 3.0.7 on 2020-11-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clickcollect", "0005_clickablecollectable_collectable_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clickablecollectable",
            name="collectable_token",
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
