# Generated by Django 3.2.11 on 2022-03-30 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('press', '0003_auto_20220329_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pressmention',
            name='og_image',
            field=models.ImageField(blank=True, upload_to='press_mention/open_graph/'),
        ),
    ]
