# Generated by Django 4.0.4 on 2022-08-25 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("press", "0006_alter_pressmention_og_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pressmention",
            name="article_link",
            field=models.URLField(max_length=255, unique=True),
        ),
    ]
